# Generated by Django 5.2.1 on 2025-05-29 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('spotify', 'Spotify')], max_length=50, verbose_name='Social media platform')),
                ('access_token', models.BinaryField(max_length=50)),
                ('refresh_token', models.BinaryField(blank=True, max_length=50, null=True)),
                ('platform_user_id', models.CharField(blank=True, max_length=256, null=True, verbose_name='Social media platform user ID')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'social_credentials',
                'unique_together': {('user', 'platform')},
            },
        ),
    ]
