# Generated by Django 5.2.1 on 2025-05-31 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_integration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialcredential',
            name='access_token',
            field=models.BinaryField(max_length=500),
        ),
        migrations.AlterField(
            model_name='socialcredential',
            name='refresh_token',
            field=models.BinaryField(blank=True, max_length=500, null=True),
        ),
    ]
