# Generated by Django 5.2.1 on 2025-06-01 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_integration', '0002_alter_socialcredential_access_token_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('spotify', 'Spotify')], max_length=50, verbose_name='Social media platform')),
                ('external_id', models.CharField(max_length=50, unique=True, verbose_name='External post ID')),
                ('external_url', models.URLField(max_length=250, verbose_name='Link to entity (song, artist, etc...) on Spotify')),
                ('external_username', models.CharField(max_length=100, verbose_name="Link to user's profile on Spotify")),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date of event')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title of the post')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Text of the post')),
                ('videos_url', models.JSONField(blank=True, null=True, verbose_name='Videos URL')),
                ('images_url', models.JSONField(blank=True, null=True, verbose_name='Images URL')),
                ('links_url', models.JSONField(blank=True, null=True, verbose_name='Links URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'social_posts',
                'unique_together': {('user', 'platform', 'external_url')},
            },
        ),
    ]
