# Generated by Django 5.2.1 on 2025-06-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_integration', '0004_socialpost_post_type_alter_socialpost_external_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='external_user_url',
            field=models.URLField(blank=True, max_length=250, null=True, verbose_name='Link to external user profile'),
        ),
    ]
