[project]
name = "spotify_integration"
version = "0.1.0"
description = "Spotify intergration"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2.1",
]

[dependency-groups]
dev = [
    "django-debug-toolbar>=5.2.0",
]
prod = [
    "gunicorn>=23.0.0",
]
